import { Geist, Geist_Mono, Comme } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const comme = Comme({
  variable: "--font-comme",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Bytequest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${comme.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
